mebay/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/ads/new', to: 'ads#new'
  post '/ads/create', to: 'ads#create'
  get '/ads/:id/edit', to: 'ads#edit'
  put '/ads/:id/update', to: 'ads#update'
  delete'/ads/:id/delete', to: 'ads#destroy', as: 'delete'
  get '/ads/:id', to: 'ads#show'
  get '/ads/', to: 'ads#index'

end

mebay/app/models/ad.rb
class Ad < ApplicationRecord
  validates_presence_of :name, :price
  validates_numericality_of :price, :seller_id
end

mebay/app/controllers/ads_controller.rb
class AdsController < ApplicationController

  before_action :check_logged_in, :only => [:edit, :update, :destroy]

  def show
    @ad = Ad.find(params[:id])
  end
  
  def index
    @ads = Ad.all
  end
  
  def new
    @ad = Ad.new
  end
  
  def create
    @ad = Ad.new(ad_params)
    # @ad.save
    # redirect_to "/ads/#{@ad.id}"
    if @ad.save
      redirect_to "/ads/#{@ad.id}"
    else
      render 'new'
    end
  end
  
  def edit
    @ad = Ad.find(params[:id])
  end
  
  def update
    @ad = Ad.find(params[:id])
    # @ad.update(ad_params)
    # redirect_to "/ads/#{@ad.id}"
    if @ad.update(ad_params)
      redirect_to "ads/#{@ad.id}"
    else
      render :edit
    end
  end
  
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to "/ads/"
  end
  
  private
  def ad_params
    params.require(:ad).permit(:name, :price, :description, :seller_id, :email, :img_url)
  end
  
  private
  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |username, password|
      username == "admin" && password == "123"
    end
  end

end

mebay/app/helpers/ads_helper.rb
module AdsHelper
end

mebay/app/views/ads/edit.html.erb
<h1>Ad: <%= @ad.name %></h1>

<%= form_with(model: @ad, url: {action: 'update'}, method: "put") do |f| %>
  <%= f.error_messages %>
  <p><b>Name</b><br/><%= f.text_field :name %></p>
  <p><b>Description</b><br/><%= f.text_area :description %></p>
  <p><b>Price</b><br/><%= f.text_field :price %></p>
  <p><b>Seller</b><br/><%= f.text_field :seller_id %></p>
  <p><b>Email</b><br/><%= f.text_area :email %></p>
  <p><b>Img url</b><br/><%= f.text_area :img_url %></p>
  <p><%= f.submit "Update" %></p>
<% end %>

mebay/app/views/ads/index.html.erb
<h1>All Ads</h1>
<ul>
<% for ad in @ads %>
  <li><a href="/ads/<%= ad.id %>"><%= ad.name %></a>
  <!--[<a href="/ads/<%= ad.id %>/delete">Delete</a>]-->
  <!--[<%= link_to "Delete", "/ads/#{ad.id}/delete", method: :delete %>]-->
  <%= button_to "Delete", delete_path(ad), method:"delete" %>
  </li>
<% end %>
</ul>

mebay/app/views/ads/new.html.erb
<h1>New ad</h1>

<%= form_with(model: @ad, url: {action: 'create'}) do |f| %>
  <%= f.error_messages %>
  <p><b>Name</b><br/><%= f.text_field :name %></p>
  <p><b>Description</b><br/><%= f.text_area :description %></p>
  <p><b>Price</b><br/><%= f.text_field :price %></p>
  <p><b>Seller</b><br/><%= f.text_field :seller_id %></p>
  <p><b>Email</b><br/><%= f.text_area :email %></p>
  <p><b>Img url</b><br/><%= f.text_area :img_url %></p>
  <p><%= f.submit "Create" %></p>
<% end %>

mebay/app/views/ads/show.html.erb
<p>
  <b>Name:</b>
  <%= @ad.name %>
</p>
<p>
  <b>Description:</b>
  <%= @ad.description %>
</p>
<p>
  <b>Price:</b>
  <%= @ad.price %>
</p>
<p>
  <b>Seller Id:</b>
  <%= @ad.seller_id %>
</p>
<p>
  <b>Email:</b>
  <%= @ad.email %>
</p>
<p>
  <img src="<%= @ad.img_url %>"/>
</p>
<p>
  <a href="/ads/<%= @ad.id %>/edit">Edit</a>
</p>

mebay/app/views/layouts/ads.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Ads: <%= controller.action_name %></title> <%= stylesheet_link_tag 'default.css' %>
</head>
<body>
<div id="wrapper">
<div id="header">
<div>
<h1>MeBay</h1>
<ul id="nav">
<li><a href="/ads/">All Ads</a></li>
</ul>
</div>
</div>
<div id="content">
<%= yield %>
</div>
<div id="clearfooter"></div>
</div>
<div id="footer"></div>
</body>