coconut/config/routes.rb
Rails.application.routes.draw do
  resources :seats
  resources :flights
  get 'flights/:flight_id/seats',  to: 'seats#flight_seats'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

coconut/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

coconut/app/models/flight.rb
class Flight < ApplicationRecord
  has_many :seats
end

coconut/app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :flight
  
  validates_presence_of :name, :baggage
  validates_numericality_of :baggage
  validate :validate_baggage_allowance
  validate :validate_booking_capacity
    
  def validate_baggage_allowance
    if baggage and baggage > flight.baggage_allowance
      errors.add(:base, "Your baggage exceeds the flights baggage allowance")
    end
  end
  
  def validate_booking_capacity
    if flight.seats.size >= flight.capacity
      errors.add(:base, "The booking capacity is full")
    end
  end
end

coconut/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

coconut/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:id, :departure, :arrival, :destination, :baggage_allowance, :capacity)
    end
end

coconut/app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: %i[ show edit update destroy ]

  # GET /seats or /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1 or /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats or /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to seat_url(@seat), notice: "Seat was successfully created." }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1 or /seats/1.json
  def update
    flight_id = @seat.flight_id
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to flight_url(flight_id), notice: "Seat was successfully updated." }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1 or /seats/1.json
  def destroy
    flight_id = @seat.flight_id
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to flight_path(flight_id), notice: "Seat was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def flight_seats
    @flight = Flight.find(params[:flight_id])
    render :partial => '/flights/seat_list', :locals => {:seats => @flight.seats}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seat_params
      params.require(:seat).permit(:id, :flight_id, :name, :baggage)
    end
end

coconut/app/helpers/application_helper.rb
module ApplicationHelper
  ActionView::Base.default_form_builder = StandardBuilder
end

coconut/app/helpers/flights_helper.rb
module FlightsHelper
end

coconut/app/helpers/seats_helper.rb
module SeatsHelper
end

coconut/app/helpers/standard_builder.rb
class StandardBuilder < ActionView::Helpers::FormBuilder
  def error_messages
    return unless object.respond_to?(:errors) && object.errors.any?

    errors_list = ""
    errors_list << @template.content_tag(:span, "There are errors!", :class => "title-error")
    errors_list << object.errors.full_messages.map { |message| @template.content_tag(:li, message) }.join("\n")

    @template.content_tag(:ul, errors_list.html_safe, :class => "error-recap round-border")
  end
end

coconut/app/views/flights/_new_seat.html.erb
<h1>New seat</h1>
<%= form_with(model: seat) do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :flight_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :baggage %><br />
    <%= f.text_field :baggage %>
  </p>
  <p>
    <%= f.submit "Create new seat" %>
  </p>
<% end %>

coconut/app/views/flights/_seat_list.html.erb
<h1>Listing seats</h1>

<table>
  <tr>
    <th>Flight</th>
    <th>Name</th>
    <th>Baggage</th>
  </tr>

<% for seat in seats %>
  <tr>
    <td><%=h seat.flight_id %></td>
    <td><%=h seat.name %></td>
    <td><%=h seat.baggage %></td>
    <td><%= link_to 'Show', seat %></td>
    <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
    <td><%= link_to 'Destroy', seat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

coconut/app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<% form_for(@flight) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :departure %><br />
    <%= f.datetime_select :departure %>
  </p>
  <p>
    <%= f.label :arrival %><br />
    <%= f.datetime_select :arrival %>
  </p>
  <p>
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </p>
  <p>
    <%= f.label :baggage_allowance %><br />
    <%= f.text_field :baggage_allowance %>
  </p>
  <p>
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

coconut/app/views/flights/index.html.erb
<h1>Listing flights</h1>

<table>
  <tr>
    <th>Departure</th>
    <th>Arrival</th>
    <th>Destination</th>
    <th>Baggage allowance</th>
    <th>Capacity</th>
  </tr>

<% for flight in @flights %>
  <tr>
    <td><%=h flight.departure %></td>
    <td><%=h flight.arrival %></td>
    <td><%=h flight.destination %></td>
    <td><%=h flight.baggage_allowance %></td>
    <td><%=h flight.capacity %></td>
    <td><%= link_to 'Show', flight %></td>
    <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
    <td><%= link_to 'Destroy', flight, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New flight', new_flight_path %>

coconut/app/views/flights/new.html.erb
<h1>New flight</h1>

<% form_for(@flight) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :departure %><br />
    <%= f.datetime_select :departure %>
  </p>
  <p>
    <%= f.label :arrival %><br />
    <%= f.datetime_select :arrival %>
  </p>
  <p>
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </p>
  <p>
    <%= f.label :baggage_allowance %><br />
    <%= f.text_field :baggage_allowance %>
  </p>
  <p>
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', flights_path %>

coconut/app/views/flights/show.html.erb
<p>
  <b>Departure:</b>
  <%=h @flight.departure %>
</p>

<p>
  <b>Arrival:</b>
  <%=h @flight.arrival %>
</p>

<p>
  <b>Destination:</b>
  <%=h @flight.destination %>
</p>

<p>
  <b>Baggage allowance:</b>
  <%=h @flight.baggage_allowance %>
</p>

<p>
  <b>Capacity:</b>
  <%=h @flight.capacity %>
</p>

<%= render :partial => 'new_seat', 
           :locals => {
             :seat => Seat.new(
               :flight_id => @flight.id)} %>

<%= render :partial => 'seat_list',
           :locals => {
             :seats => @flight.seats} %>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

coconut/app/views/layouts/flights.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Flights: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

coconut/app/views/layouts/seats.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Seats: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

coconut/app/views/seats/_form.html.erb
<%= form_with(model: seat) do |form| %>
  <% if seat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
        <% seat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :flight_id, style: "display: block" %>
    <%= form.number_field :flight_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :baggage, style: "display: block" %>
    <%= form.text_field :baggage %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

coconut/app/views/seats/_seat.html.erb
<div id="<%= dom_id seat %>">
  <p>
    <strong>Id:</strong>
    <%= seat.id %>
  </p>

  <p>
    <strong>Flight:</strong>
    <%= seat.flight_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= seat.name %>
  </p>

  <p>
    <strong>Baggage:</strong>
    <%= seat.baggage %>
  </p>

</div>

coconut/app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%= link_to "Show this seat", @seat %> |
  <%= link_to "Back to seats", seats_path %>
</div>

coconut/app/views/seats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Seats</h1>

<div id="seats">
  <% @seats.each do |seat| %>
    <%= render seat %>
    <p>
      <%= link_to "Show this seat", seat %>
    </p>
  <% end %>
</div>

<%= link_to "New seat", new_seat_path %>

coconut/app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%= link_to "Back to seats", seats_path %>
</div>

coconut/app/views/seats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @seat %>

<div>
  <%= link_to "Edit this seat", edit_seat_path(@seat) %> |
  <%= link_to "Back to seats", seats_path %>

  <%= button_to "Destroy this seat", @seat, method: :delete %>
</div>