workout_app/config/routes.rb
Rails.application.routes.draw do
  get '/client_workouts/find', to: 'client_workouts#find', as: 'find'
  resources :client_workouts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

workout_app/app/models/client_workout.rb
class ClientWorkout < ApplicationRecord
end

workout_app/app/controllers/client_workouts_controller.rb
class ClientWorkoutsController < ApplicationController
  before_action :set_client_workout, only: %i[ show edit update destroy ]

  # GET /client_workouts or /client_workouts.json
  
  def index
    @client_workouts = ClientWorkout.all
  end

  # GET /client_workouts/1 or /client_workouts/1.json
  def show
  end

  # GET /client_workouts/new
  def new
    @client_workout = ClientWorkout.new
  end

  # GET /client_workouts/1/edit
  def edit
  end

  # POST /client_workouts or /client_workouts.json
  def create
    @client_workout = ClientWorkout.new(client_workout_params)

    respond_to do |format|
      if @client_workout.save
        format.html { redirect_to client_workout_url(@client_workout), notice: "Client workout was successfully created." }
        format.json { render :show, status: :created, location: @client_workout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_workouts/1 or /client_workouts/1.json
  def update
    respond_to do |format|
      if @client_workout.update(client_workout_params)
        format.html { redirect_to client_workout_url(@client_workout), notice: "Client workout was successfully updated." }
        format.json { render :show, status: :ok, location: @client_workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def find
    #@client_workouts = ClientWorkout.where(client_name: params[:search_string])
    #  .or(ClientWorkout.where(trainer: params[:search_string]))
    search = params[:search_string]
    @client_workouts = ClientWorkout.where("client_name = ? OR trainer = ?", search, search)
  end


  # DELETE /client_workouts/1 or /client_workouts/1.json
  def destroy
    @client_workout.destroy

    respond_to do |format|
      format.html { redirect_to client_workouts_url, notice: "Client workout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_workout
      @client_workout = ClientWorkout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_workout_params
      params.require(:client_workout).permit(:client_name, :trainer, :duration_mins, :date_of_workout, :paid_amount)
    end
end

workout_app/app/helpers/application_helper.rb
module ApplicationHelper
end

workout_app/app/helpers/client_workouts_helper.rb
module ClientWorkoutsHelper
end

workout_app/app/views/client_workouts/_client_workout.html.erb
<div id="<%= dom_id client_workout %>">
  <p>
    <strong>Client name:</strong>
    <%= client_workout.client_name %>
  </p>

  <p>
    <strong>Trainer:</strong>
    <%= client_workout.trainer %>
  </p>

  <p>
    <strong>Duration mins:</strong>
    <%= client_workout.duration_mins %>
  </p>

  <p>
    <strong>Date of workout:</strong>
    <%= client_workout.date_of_workout %>
  </p>

  <p>
    <strong>Paid amount:</strong>
    <%= client_workout.paid_amount %>
  </p>

</div>

workout_app/app/views/client_workouts/_form.html.erb
<%= form_with(model: client_workout) do |form| %>
  <% if client_workout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client_workout.errors.count, "error") %> prohibited this client_workout from being saved:</h2>

      <ul>
        <% client_workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_name, style: "display: block" %>
    <%= form.text_field :client_name %>
  </div>

  <div>
    <%= form.label :trainer, style: "display: block" %>
    <%= form.text_field :trainer %>
  </div>

  <div>
    <%= form.label :duration_mins, style: "display: block" %>
    <%= form.number_field :duration_mins %>
  </div>

  <div>
    <%= form.label :date_of_workout, style: "display: block" %>
    <%= form.date_field :date_of_workout %>
  </div>

  <div>
    <%= form.label :paid_amount, style: "display: block" %>
    <%= form.text_field :paid_amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

workout_app/app/views/client_workouts/edit.html.erb
<h1>Editing client workout</h1>

<%= render "form", client_workout: @client_workout %>

<br>

<div>
  <%= link_to "Show this client workout", @client_workout %> |
  <%= link_to "Back to client workouts", client_workouts_path %>
</div>

workout_app/app/views/client_workouts/find.html.erb
<h1>Listing client_workouts for <%= params[:search_string] %></h1>
<table>
<tr>
<th>Trainer</th>
<th>Duration mins</th>
<th>Date of workout</th>
<th>Paid amount</th>
</tr>
<% for client_workout in @client_workouts %>
<tr>
<td><%=h client_workout.trainer %></td>
<td><%=h client_workout.duration_mins %></td>
<td><%=h client_workout.date_of_workout %></td>
<td><%=h client_workout.paid_amount %></td>
<td><%= link_to "Show", client_workout %></td>
<td><%= link_to "Edit", edit_client_workout_path(client_workout) %></td>
<td><%= link_to "Destroy", client_workout, :confirm => "Are you sure?", :method => :delete %></td>
</tr>
<% end %>
</table>

workout_app/app/views/client_workouts/index.html.erb
<h1>Client workouts</h1>

<div id="client_workouts">
  <table>
    <tr>
      <th>Client name</th>
      <th>Trainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th></th>
    </tr>
    <% @client_workouts.each do |cw| %>
      <tr>
        <td><%= cw.client_name %></td>
        <td><%= cw.trainer %></td>
        <td><%= cw.duration_mins %></td>
        <td><%= cw.date_of_workout %></td>
        <td><%= cw.paid_amount %></td>
        <td><%= link_to "Show", client_workout_path(cw) %> <%= link_to "Edit", edit_client_workout_path(cw) %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "New client workout", new_client_workout_path %>

workout_app/app/views/client_workouts/new.html.erb
<h1>New client workout</h1>

<%= render "form", client_workout: @client_workout %>

<br>

<div>
  <%= link_to "Back to client workouts", client_workouts_path %>
</div>

workout_app/app/views/client_workouts/show.html.erb
<%= render @client_workout %>

<div>
  <%= link_to "Edit this client workout", edit_client_workout_path(@client_workout) %> |
  <%= link_to "Back to client workouts", client_workouts_path %>

  <%= button_to "Destroy this client workout", @client_workout, method: :delete %>
</div>

workout_app/app/views/layouts/client_workouts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<title>ClientWorkouts: <%= controller.action_name %></title>
<%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<span style="text-align: right">
  <%= form_tag("/client_workouts/find", method: :get) do %>
    <%= text_field_tag :search_string %>
    <%= submit_tag "Search" %>
  <% end %>
</span>
<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>